"use client";

import { useEffect, useState } from "react";
import { supabase } from "@/lib/supabaseClient";
import jsPDF from "jspdf";
import "jspdf-autotable";

export interface BillRecord {
  id: string;
  bill_number: string;
  description: string;
  amount: number;
  category: string;
  status: string;
  created_at: string;
}

export default function FinanceManagement() {
  const [bills, setBills] = useState<BillRecord[]>([]);
  const [loading, setLoading] = useState(true);

  // Form States
  const [billNum, setBillNum] = useState("");
  const [desc, setDesc] = useState("");
  const [amount, setAmount] = useState("");
  const [category, setCategory] = useState("Petty Cash");
  const [status, setStatus] = useState("Pending");

  useEffect(() => {
    fetchBills();

    // Real-time updates subscription
    const channel = supabase
      .channel("realtime-bills")
      .on("postgres_changes", { event: "*", schema: "public", table: "bills" }, () => {
        fetchBills();
      })
      .subscribe();

    return () => {
      supabase.removeChannel(channel);
    };
  }, []);

  const fetchBills = async () => {
    try {
      const { data, error } = await supabase
        .from("bills")
        .select("*")
        .order("created_at", { ascending: false });

      if (error) throw error;
      if (data) {
        const typedData: BillRecord[] = data.map((item: Record<string, any>) => ({
          id: String(item.id ?? ""),
          bill_number: String(item.bill_number ?? ""),
          description: String(item.description ?? ""),
          amount: Number(item.amount ?? 0),
          category: String(item.category ?? "Petty Cash"),
          status: String(item.status ?? "Pending"),
          created_at: String(item.created_at ?? new Date().toISOString()),
        }));
        setBills(typedData);
      }
    } catch (error: any) {
      alert("Error fetching bills: " + (error?.message ?? "Unknown error"));
    } finally {
      setLoading(false);
    }
  };

  const handleAddBill = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!billNum || !desc || !amount) {
      alert("Please fill all fields");
      return;
    }

    try {
      const numericAmount = parseFloat(amount) || 0;
      // 1. Insert Data into Supabase
      const { error } = await supabase.from("bills").insert([
        {
          bill_number: billNum,
          description: desc,
          amount: numericAmount,
          category: category,
          status: status,
        },
      ]);

      if (error) throw error;

      // 2. 🔥 Auto Email Sending Trigger (Background Notification)
      try {
        await fetch('/api/send-email', {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({
            to: 'sandun@browns.com',
            subject: `⚠️ ALERT: New Bill Updated - ${billNum}`,
            htmlContent: `
              <div style="font-family: Arial, sans-serif; max-width: 600px; border: 1px solid #e0e0e0; padding: 20px; border-radius: 10px;">
                <h2 style="color: #f59e0b;">Browns Engineering & Construction ERP</h2>
                <p>A new billing record has been successfully updated in the system portal.</p>
                <hr style="border: 0; border-top: 1px solid #eeeeee;" />
                <table style="width: 100%; border-collapse: collapse; margin-top: 15px;">
                  <tr>
                    <td style="padding: 8px 0; font-weight: bold; color: #555555;">Bill Number:</td>
                    <td style="padding: 8px 0; color: #333333;">${billNum}</td>
                  </tr>
                  <tr>
                    <td style="padding: 8px 0; font-weight: bold; color: #555555;">Description:</td>
                    <td style="padding: 8px 0; color: #333333;">${desc}</td>
                  </tr>
                  <tr>
                    <td style="padding: 8px 0; font-weight: bold; color: #555555;">Category:</td>
                    <td style="padding: 8px 0; color: #333333;">${category}</td>
                  </tr>
                  <tr>
                    <td style="padding: 8px 0; font-weight: bold; color: #555555;">Amount:</td>
                    <td style="padding: 8px 0; color: #10b981; font-weight: bold;">Rs. ${numericAmount.toLocaleString()}</td>
                  </tr>
                  <tr>
                    <td style="padding: 8px 0; font-weight: bold; color: #555555;">Current Status:</td>
                    <td style="padding: 8px 0;"><span style="background-color: #fef3c7; color: #d97706; padding: 4px 8px; border-radius: 4px; font-size: 12px; font-weight: bold;">${status}</span></td>
                  </tr>
                </table>
                <hr style="border: 0; border-top: 1px solid #eeeeee; margin-top: 20px;" />
                <p style="font-size: 12px; color: #888888; margin-top: 20px;">This is an automated operational alert generated by Browns Construction ERP Framework.</p>
              </div>
            `
          }),
        });
      } catch (emailErr) {
        console.error("Email notification failed to send:", emailErr);
      }

      // 3. Clear Form Fields on success
      setBillNum("");
      setDesc("");
      setAmount("");
      alert("Bill recorded and alert email sent successfully!");
      
    } catch (error: any) {
      alert("Error adding bill: " + (error?.message ?? "Unknown error"));
    }
  };

  // PDF Export Function
  const exportToPDF = () => {
    const doc = new jsPDF() as any;
    doc.text("Browns Engineering & Construction - Finance Report", 14, 15);
    
    const tableRows = bills.map((b) => [
      b.bill_number ?? "N/A",
      b.description ?? "N/A",
      b.category ?? "N/A",
      `Rs. ${(b.amount ?? 0).toLocaleString()}`,
      b.status ?? "Pending",
      b.created_at ? new Date(b.created_at).toLocaleDateString() : "N/A",
    ]);

    doc.autoTable({
      head: [["Bill No", "Description", "Category", "Amount", "Status", "Date"]],
      body: tableRows,
      startY: 22,
    });

    doc.save(`Browns_Finance_Report_${new Date().toISOString().split('T')[0]}.pdf`);
  };

  return (
    <div className="p-6 bg-slate-900 min-h-screen text-white">
      <div className="max-w-6xl mx-auto space-y-8">
        <div className="flex justify-between items-center">
          <div>
            <h1 className="text-2xl font-bold text-amber-500">Browns Engineering & Construction</h1>
            <p className="text-slate-400 text-sm">Finance & Petty Cash Ledger Portal</p>
          </div>
          <button onClick={exportToPDF} className="bg-emerald-600 hover:bg-emerald-700 text-white font-bold py-2 px-4 rounded transition text-sm">
            Export Report to PDF
          </button>
        </div>

        {/* Bill Entry Form */}
        <form onSubmit={handleAddBill} className="bg-slate-800 p-6 rounded-xl border border-slate-700 grid grid-cols-1 md:grid-cols-5 gap-4">
          <h2 className="text-lg font-semibold md:col-span-5 text-slate-200">Update / Record New Bill</h2>
          
          <input type="text" placeholder="Bill/Voucher Number" value={billNum} onChange={(e) => setBillNum(e.target.value)} className="p-2.5 rounded bg-slate-700 border border-slate-600 text-white" required />
          <input type="text" placeholder="Description of expenditure" value={desc} onChange={(e) => setDesc(e.target.value)} className="p-2.5 rounded bg-slate-700 border border-slate-600 text-white" required />
          <input type="number" placeholder="Amount (LKR)" value={amount} onChange={(e) => setAmount(e.target.value)} className="p-2.5 rounded bg-slate-700 border border-slate-600 text-white" required />
          
          <select value={category} onChange={(e) => setCategory(e.target.value)} className="p-2.5 rounded bg-slate-700 border border-slate-600 text-white">
            <option value="Petty Cash">Petty Cash</option>
            <option value="Materials">Materials</option>
            <option value="Fuel">Fuel</option>
            <option value="Transport">Transport</option>
          </select>

          <select value={status} onChange={(e) => setStatus(e.target.value)} className="p-2.5 rounded bg-slate-700 border border-slate-600 text-white">
            <option value="Pending">Pending</option>
            <option value="Approved">Approved</option>
            <option value="Paid">Paid</option>
          </select>

          <button type="submit" className="md:col-span-5 bg-amber-500 hover:bg-amber-600 text-slate-900 font-bold py-2.5 rounded transition">
            Save Record & Send Alert
          </button>
        </form>

        {/* Bills Registry Table */}
        <div className="bg-slate-800 rounded-xl border border-slate-700 overflow-hidden">
          <div className="p-4 border-b border-slate-700">
            <h2 className="text-lg font-semibold text-slate-200">Corporate Bills Ledger</h2>
          </div>

          {loading ? (
            <p className="p-6 text-center text-slate-400">Loading billing files...</p>
          ) : (
            <div className="overflow-x-auto">
              <table className="w-full text-left border-collapse">
                <thead>
                  <tr className="bg-slate-700/50 text-slate-300 text-sm">
                    <th className="p-3">Bill No</th>
                    <th className="p-3">Description</th>
                    <th className="p-3">Category</th>
                    <th className="p-3">Amount</th>
                    <th className="p-3">Status</th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-slate-700 text-slate-300">
                  {bills.map((b) => (
                    <tr key={b.id} className="hover:bg-slate-700/30 transition text-sm">
                      <td className="p-3 font-semibold text-amber-400">{b.bill_number ?? "N/A"}</td>
                      <td className="p-3">{b.description ?? "N/A"}</td>
                      <td className="p-3 text-slate-400">{b.category ?? "N/A"}</td>
                      <td className="p-3 text-emerald-400">Rs. {(b.amount ?? 0).toLocaleString()}</td>
                      <td className="p-3">
                        <span className={`px-2 py-0.5 rounded text-xs font-bold ${
                          b.status === 'Paid' ? 'bg-emerald-500/20 text-emerald-400' :
                          b.status === 'Approved' ? 'bg-blue-500/20 text-blue-400' : 'bg-amber-500/20 text-amber-400'
                        }`}>{b.status ?? "Pending"}</span>
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          )}
        </div>
      </div>
    </div>
  );
}
